exec:
	java -cp build:/usr/share/java/postgis.jar:/usr/share/java/postgresql.jar ImporteurJDBC /home/leopold/SIG/m2info/SIG/depot/android/res/raw/zones.txt

comp:
	javac src/ImporteurJDBC.java -d build -cp /usr/share/java/postgis.jar:/usr/share/java/postgresql.jar -sourcepath src

